web/router.ex
defmodule SwapItUp.Router do
  use SwapItUp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession, key: :default
    plug Guardian.Plug.LoadResource, key: :default
  end

  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
    plug Guardian.Plug.LoadResource, key: :admin
  end

  pipeline :impersonation_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
  end
  
  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SwapItUp do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/users/signup", UserController, :new
    post "/users/", UserController, :create 

    get "/markets", MarketController, :index
    get "/markets/new", MarketController, :new
    post "/markets", MarketController, :create
  end

  scope "/u", SwapItUp do
    pipe_through [:browser, :browser_auth]

    get "/:username", UserController, :show
    get "/:username/edit", UserController, :edit
    patch "/:username", UserController, :update
    put "/:username", UserController, :update
  end

  scope "/m", SwapItUp do
    pipe_through [:browser, :browser_auth]

    resources "/", MarketController, param: "name", except: [:new, :create, :index] do
      get "/submit", PostController, :new, as: :post
      post "/", PostController, :create, as: :post
      resources "/post", PostController, except: [:new, :create], as: :post
    end
    
  end



  # This scope is inteded for admin users
  # Normal users can only go through the login page
  scope "/admin", SwapItUp.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth, :impersonation_browser_auth]

    resources "/login", SessionController, only: [:new, :create]
    get "/logout", SessionController, :logout
    delete "/logout", SessionController, :logout, as: :logout
    post "/impersonate/:username", SessionController, :impersonate, as: :impersonate
    delete "/impersonate", SessionController, :stop_impersonating

    get "/users", UserController, :index
    delete "/users/:username", UserController, :delete
  end


  # Other scopes may use custom stacks.
  # scope "/api", SwapItUp do
  #   pipe_through :api
  # end
end

web/models/market.ex
defmodule SwapItUp.Market do
  use SwapItUp.Web, :model

  schema "markets" do
    field :name, :string
    field :date_created, Ecto.DateTime

    has_many :posts, SwapItUp.Post
    has_many :subscribers, SwapItUp.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> Ecto.Changeset.change(%{date_created: Ecto.DateTime.utc()})
    |> cast(params, [:name, :date_created])
    |> validate_required([:name, :date_created])
    |> unique_constraint(:name)
  end
end

web/controllers/market_controller.ex
defmodule SwapItUp.MarketController do
  use SwapItUp.Web, :controller

  alias SwapItUp.Market

  plug EnsureAuthenticated, [key: :default, handler: SwapItUp.Unauth] when action in [:new, :create, :edit, :update]

  def index(conn, _params, _current_user, _claims) do
    markets = Repo.all(Market)
    render(conn, "index.html", markets: markets)
  end

  def new(conn, _params, _current_user, _claims) do
    changeset = Market.changeset(%Market{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"market" => market_params}, _current_user, _claims ) do
    changeset = Market.changeset(%Market{}, market_params)

    case Repo.insert(changeset) do
      {:ok, _market} ->
        conn
        |> put_flash(:info, "Market created successfully.")
        |> redirect(to: market_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"name" => market_name}, _current_user, _claims) do
    market = Repo.get_by(Market, name: market_name)
    market = Repo.preload(market, :posts)
    render(conn, "show.html", market: market)
  end

  def edit(conn, %{"name" => market_name}, _current_user, _claims) do
    market = Repo.get_by(Market, name: market_name)
    changeset = Market.changeset(market)
    render(conn, "edit.html", market: market, changeset: changeset)
  end

  def update(conn, %{"name" => market_name, "market" => market_params}, _current_user, _claims) do
    market = Repo.get_by(Market, name: market_name)
    changeset = Market.changeset(market, market_params)

    case Repo.update(changeset) do
      {:ok, market} ->
        conn
        |> put_flash(:info, "Market updated successfully.")
        |> redirect(to: market_path(conn, :show, market))
      {:error, changeset} ->
        render(conn, "edit.html", market: market, changeset: changeset)
    end
  end
end

web/views/market_view.ex
defmodule SwapItUp.MarketView do
  use SwapItUp.Web, :view

  def make_title(post) do
    if post.buying do
      post.want <> post.have
    else
      post.have <> post.want
    end
  end
end

web/templates/market/edit.html.eex
<h2>Edit market</h2>

<%= render "form.html", changeset: @changeset,
                        action: market_path(@conn, :update, @market) %>

<%= link "Back", to: market_path(@conn, :index) %>

web/templates/market/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/market/index.html.eex
<h2>Listing markets</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date created</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for market <- @markets do %>
    <tr>
      <td><%= market.name %></td>
      <td><%= market.date_created %></td>

      <td class="text-right">
        <%= link "Show", to: market_path(@conn, :show, market.name), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: market_path(@conn, :edit, market.name), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New market", to: market_path(@conn, :new) %>

web/templates/market/new.html.eex
<h2>New market</h2>

<%= render "form.html", changeset: @changeset,
                        action: market_path(@conn, :create) %>

web/templates/market/show.html.eex
<h2><%= @market.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date created</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
 <%= for post <- @market.posts do %>
    <tr>
      <td> 
        <%= link make_title(post), to: market_post_path(@conn, :show, @market.name, post.id) %>
      </td>
      <td class="text-right">
        <%= link "Edit", to: market_post_path(@conn, :edit, @market.name, post.id), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>


  <li>
    <strong> <%= link "New Post", to: market_post_path(@conn, :new, @market.name) %></strong>
  </li>