web/router.ex
defmodule SwapItUp.Router do
  use SwapItUp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession, key: :default
    plug Guardian.Plug.LoadResource, key: :default
  end

  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
    plug Guardian.Plug.LoadResource, key: :admin
  end

  pipeline :impersonation_browser_auth do
    plug Guardian.Plug.VerifySession, key: :admin
  end
  
  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SwapItUp do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/users/signup", UserController, :new
    post "/users/", UserController, :create 

    get "/markets", MarketController, :index
    get "/markets/new", MarketController, :new
    post "/markets", MarketController, :create
  end

  scope "/u", SwapItUp do
    pipe_through [:browser, :browser_auth]

    get "/:username", UserController, :show
    get "/:username/edit", UserController, :edit
    patch "/:username", UserController, :update
    put "/:username", UserController, :update
  end

  scope "/m", SwapItUp do
    pipe_through [:browser, :browser_auth]

    resources "/", MarketController, param: "name", except: [:new, :create, :index] do
      get "/submit", PostController, :new, as: :post
      post "/", PostController, :create, as: :post
      resources "/post", PostController, except: [:new, :create], as: :post
    end
    
  end



  # This scope is inteded for admin users
  # Normal users can only go through the login page
  scope "/admin", SwapItUp.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth, :impersonation_browser_auth]

    resources "/login", SessionController, only: [:new, :create]
    get "/logout", SessionController, :logout
    delete "/logout", SessionController, :logout, as: :logout
    post "/impersonate/:username", SessionController, :impersonate, as: :impersonate
    delete "/impersonate", SessionController, :stop_impersonating

    get "/users", UserController, :index
    delete "/users/:username", UserController, :delete
  end


  # Other scopes may use custom stacks.
  # scope "/api", SwapItUp do
  #   pipe_through :api
  # end
end

web/views/admin/layout_view.ex
defmodule SwapItUp.Admin.LayoutView do
  use SwapItUp.Web, :view
end

web/views/layout_view.ex
defmodule SwapItUp.LayoutView do
  use SwapItUp.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SwapItUp!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <ol class="breadcrumb text-right">
          <%= if logged_in?(@conn) do %>
            <li><%= current_user(@conn).username %></li>
            <li><%= link "Log out", to: session_path(@conn, :delete), method: "delete" %></li>

            <%= if admin_logged_in?(@conn) do %>
              <li><%= link "Stop impersonating #{current_user(@conn).username}", 
                        to: admin_session_path(@conn, :stop_impersonating),
                        method: "DELETE",
                        class: "btn btn-warining"
                  %>
                  <li><%= link "Log out as Admin", to: admin_session_path(@conn, :delete), method: "DELETE" %>
            <% end %>

          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %>
            <li><%= link "Log in", to: session_path(@conn, :new) %>
            <% end %>
          </ol>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>